# Global ServerName
ServerName app.bobnuri.local

<VirtualHost *:80>
    ServerName app.bobnuri.local

    ProxyRequests Off
    ProxyPreserveHost On

    # Set headers for the backend app
    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "80"

    # Forward traffic to the 'app' service container
    ProxyPass / http://app:80/
    ProxyPassReverse / http://app:80/

    # Logging
    ErrorLog "logs/bobnuri-error.log"
    CustomLog "logs/bobnuri-access.log" combined
</VirtualHost>

# HTTPS TODO:
# <VirtualHost *:443>
#     ServerName app.bobnuri.local
#     SSLEngine on
#     ...
# </VirtualHost>
