ServerName bobnuri.o-r.kr

Listen 443

<VirtualHost *:80>
    ServerName bobnuri.o-r.kr
    RewriteEngine On
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName bobnuri.o-r.kr

    SSLEngine on
    SSLCertificateFile /usr/local/apache2/conf/origin.pem
    SSLCertificateKeyFile /usr/local/apache2/conf/origin.key

    ProxyRequests Off
    ProxyPreserveHost On

    RequestHeader set X-Forwarded-Proto 'https'
    RequestHeader set X-Forwarded-Port '443'

    # n8n 설정 (경로를 인식하도록 맨 위에 배치)
    ProxyPass /n8n http://n8n:5678/
    ProxyPassReverse /n8n http://n8n:5678/

    # 기본 앱 설정
    ProxyPass / http://app:80/
    ProxyPassReverse / http://app:80/

    ErrorLog 'logs/bobnuri-ssl-error.log'
    CustomLog 'logs/bobnuri-ssl-access.log' combined
</VirtualHost>
